### ISSUE TITLE
test the ~20 non-CRAN packages on Omega Hat

### ISSUE THREAD

**Issue by wibeasley** [cran-task-views/WebTechnologies#500]
We list a lot of omega hat packages that have been dormant for 10+ years.  Many of these were important for our ecosystem when Duncan released them, but I imagine some can't even be installed if the code hasn't been touched in a decade.  I don't want to send our readers on fruitless journeys.

I'll write a script that iterates and determines which ones are installable.

**Comment by wibeasley** [comment]
completed.  The key commit was @zeileis's suggested explanation included in commit a309f4159b24c8add1b3757c2310e8b0b736f432

**Comment by zeileis** [comment]
Thanks for this. It made me notice that you have links to other task views as standard Markdown links. However, the preferred solution would be to use the `r view(...)` tag for this. Usually, the related task views are mentioned somewhere in the text and then the extra link is auto-generated in the "Other resources" section at the very end of the task view. For an example, see:

<https://cran.r-project.org/web/views/Econometrics.html#time-series-data-and-models>

This mentions `r view("TimeSeries")` at the beginning of the section. And because of this the link is also repeated in the "Other resources" section at the very end.

I would recommend that you also follow this convention for the WebTechnologies task view.
