### ISSUE TITLE
Package 'ganalytics' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/WebTechnologies#519]
Package [ganalytics](https://CRAN.R-project.org/package=ganalytics) is currently listed in CRAN Task View [WebTechnologies](https://CRAN.R-project.org/view=WebTechnologies) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by wibeasley** [comment]
@pachadotdev, I removed it entirely.  It's been 4.5 years since the last CRAN update, and "the maintainer claims to no longer maintains it" according to the current CRAN page.

I wish the [other package mentioned](https://code.markedmondson.me/googleAnalyticsR/) something about OAuth2.  If the archived package has a feature the new one lacks, it might be a nice bread crumb trail for someone wanting to add that feature to the new package.  But the new package's readme does mention the (now) archived package.

https://cran.r-project.org/src/contrib/Archive/ganalytics/

![image](https://github.com/cran-task-views/WebTechnologies/assets/1372890/530ec797-47a7-4b2f-8c1d-b97c839c8726)

![image](https://github.com/cran-task-views/WebTechnologies/assets/1372890/be407565-acf4-4c0f-ab84-b9bd0ebdf285)

**Comment by pachadotdev** [comment]
thanks @wibeasley @statmath-it !
I will be more responsive now that the semester has started

**Comment by wibeasley** [comment]
No pressure from me.  My post certainly didn't require an urgent response.  Good luck on the new semester
